In [1]:
import warnings
warnings.filterwarnings("ignore")

from IPython.display import display, HTML, IFrame
import math
import ast
import numpy as np
import pandas as pd
from shapely.geometry import MultiPoint
from shapely import wkt
from scipy import stats
import shapely
import glob
import shutil
import os
import matplotlib.pyplot as plt
import bs4, re
import copy
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from urllib.request import urlopen
import requests
import json
%matplotlib inline

from pandas.io.json import json_normalize
import matplotlib.image as mpimg
import requests

In [2]:
import PIL
import os
import os.path
from PIL import Image, ImageChops

In [3]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [4]:
input_data = {'city':['Ann Arbor', 'Boulder', 'Chicago', 'DC', 'NYC', 'SF','Madison','Tulsa','Seattle'],
        'data_type':['Training','Training','Training','Training','Training','Training','Testing','Testing','Testing']}
input_df = pd.DataFrame(input_data)
input_df

        city data_type
0  Ann Arbor  Training
1    Boulder  Training
2    Chicago  Training
3         DC  Training
4        NYC  Training
5         SF  Training
6    Madison   Testing
7      Tulsa   Testing
8    Seattle   Testing

In [15]:
def toLINE(city,data_type):
  f = r'/content/gdrive/MyDrive/Columbia/2 Spring 22/ML for Urban Data/ML Final/Project Files/Urban-Mobility-Index/Data/'+ data_type +'/'+ city +'/Maps/IMG'
  overlay = Image.open("/content/gdrive/MyDrive/Columbia/2 Spring 22/ML for Urban Data/ML Final/Project Files/Urban-Mobility-Index/Script/Data Cleaning/Image Processing/Overlay.png")

  for file in os.listdir(f):
    f_img = f+"/"+file
    img = Image.open(f_img)
    img.paste(overlay, (0, 0), overlay)
    img = img.convert("RGBA")
    datas = img.getdata()

    newData = []
    for item in datas:
      if item[0] != 0 and item[1] != 0 and item[2] != 0 :
         newData.append((255, 255, 255))
      else:
        newData.append(item)

    img.putdata(newData)
    g = r'/content/gdrive/MyDrive/Columbia/2 Spring 22/ML for Urban Data/ML Final/Project Files/Urban-Mobility-Index/Data/'+ data_type +'/'+ city +'/Maps/LINE'
    g_img = g+"/"+file
    img.save(g_img)

In [16]:
n = 0

for n in range(input_df.shape[0]):
  city = input_df['city'][n]
  data_type = input_df['data_type'][n]
  toLINE(city,data_type)
  print(city)
  n = n + 1

Ann Arbor
Boulder
Chicago
DC
NYC
SF
Madison
Tulsa
Seattle